language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade setuptools
  - pip install coveralls pep8 pep257 restructuredtext_lint testfixtures
  - python setup.py install
script:
  - python setup.py test
  - pep8 --ignore=E501 *.py rdiffb/*.py tests/*.py
  - pep257 *.py rdiffb/*.py tests/*.py
  - rst-lint README
  - coverage run --source=rdiffb setup.py test
after_success:
  - coveralls